version: '3.4'

services:
  lookupapp:
    image: lookupapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CLIENT_ID=797025285452-cfa9tcf8erdfql3jtilv30tepclnnn03.apps.googleusercontent.com
      - CLIENT_SECRET=xfBHYq-whMhnBN3jknv_763y
      - REDIRECT_URI=https://developers.google.com/oauthplayground
      - REFRESH_TOKEN=1//04LJkOOh1bT35CgYIARAAGAQSNwF-L9Irag1n54HKJxkzqcbFol9tQ_oKlv7B_S2CVmr49c4LW0fT07xVbZBRkK6xX1vjtJV0zBQ
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123123
      - DB_DEFAULT=lookup-app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: lookup-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=lookup-app
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
