version: '3.4'

services:
  lookupapp:
    image: lookupapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CLIENT_ID=
      - CLIENT_SECRET=
      - REDIRECT_URI=
      - REFRESH_TOKEN=
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123123
      - DB_DEFAULT=lookup-app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: lookup-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=lookup-app
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
